export const Genero = {
    Shonen: "Shonen",
    Shojo: "Shojo",
    Seinen: "Seinen",
    Josei: "Josei",
    Kodomo: "Kodomo",
    Action: "Action",
    Adventure: "Adventure",
    MartialArts: "Martial Arts",
    Mecha: "Mecha",
    Military: "Military",
    SuperPower: "Super Power",
    Sports: "Sports",
    Fantasy: "Fantasy",
    SciFi: "SciFi",
    Space: "Space",
    Supernatural: "Supernatural",
    Magic: "Magic",
    Comedy: "Comedy",
    Vampire: "Vampire",
    Romance: "Romance",
    Drama: "Drama",
    SliceOfLife: "Slice of Life",
    School: "School",
    Music: "Music",
    Mystery: "Mystery",
    Horror: "Horror",
    Thriller: "Thriller",
    Psychological: "Psychological",
    Historical: "Historical",
    Samurai: "Samurai",
    Parody: "Parody",
    Gag: "Gag",
} as const;

export type Genero = typeof Genero[keyof typeof Genero];
